SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    dtype, 
    identifier, 
    description,
    keywords, 
    remarks, 
    synonyms, 
    title, 
    pub_scope_id
FROM 
    public.simiproduct_data_product;
