SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    delete_ts, 
    deleted_by, 
    ext1, 
    ext2, 
    ext3, 
    ext4, 
    ext5, 
    sort, 
    transparency, 
    data_set_view_id, 
    facade_layer_id
FROM 
    public.simiproduct_properties_in_facade;