SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    delete_ts, 
    deleted_by, 
    ext1, 
    ext2, 
    ext3, 
    ext4, 
    ext5, 
    sort, 
    transparency, 
    visible, 
    product_list_id, 
    single_actor_id
FROM 
    public.simiproduct_properties_in_list;