SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    sort, 
    data_set_view_id, 
    facade_layer_id
FROM 
    public.simiproduct_properties_in_facade;
