SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    sort, 
    visible, 
    product_list_id, 
    single_actor_id
FROM 
    public.simiproduct_properties_in_list;
