SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    name, 
    description_model, 
    description_override, 
    'Stellvertreter' AS type_name, 
    mandatory,  
    str_length, 
    cat_synced, 
    postgres_table_id, 
    alias,
    wms_fi_format,
    display_props4_json
FROM 
    public.simidata_table_field;
