SELECT 
    id, 
    version, 
    create_ts, 
    created_by, 
    update_ts, 
    updated_by, 
    delete_ts, 
    deleted_by, 
    ext1, 
    ext2, 
    ext3, 
    ext4, 
    ext5, 
    sort, 
    alias, 
    wms_fi_format, 
    display_props4_json, 
    table_field_id, 
    table_view_id
FROM 
    public.simidata_view_field;